"""
Seed the hybrid-RAG demo via the SQLcl MCP server:
  * policies      — refund-policy clauses with VECTOR embeddings (the unstructured side)
  * orders        — structured order facts (the relational side)
  * refund_requests — incoming requests to assess

Run:  python src/seed.py
"""
from __future__ import annotations

import asyncio

from openai import AsyncOpenAI

import config
from mcp_oracle import open_oracle_mcp, OracleMCP
from tools import _vector_literal

# title, category, clause_text
POLICIES = [
    ("Standard return window", "WINDOW",
     "Customers may return most items for a full refund within 30 days of the delivery date. "
     "Requests made after 30 days from delivery are not eligible for a refund."),
    ("Damaged or defective on arrival", "DAMAGE",
     "If an item arrives damaged, defective, or not as described, the customer is entitled to a "
     "full refund or replacement regardless of the return window, provided it is reported within "
     "14 days of delivery."),
    ("Final sale items", "FINAL_SALE",
     "Items marked as final sale or clearance are non-refundable and cannot be returned except "
     "where required by law."),
    ("Digital goods", "DIGITAL",
     "Digital products and downloads are non-refundable once the item has been downloaded or "
     "the license key has been revealed."),
    ("Late delivery compensation", "DELIVERY",
     "If an order is delivered more than 10 days after the promised date, the customer may claim "
     "a partial refund of up to 20% as goodwill, even if they keep the item."),
    ("Fraud and abuse hold", "ABUSE",
     "Refund requests from accounts with a pattern of excessive returns or suspected fraud are "
     "placed on hold and escalated to a human agent for manual review."),
]

# order_id, customer_id, product, amount, order_date, delivered_date, status, channel
ORDERS = [
    (9001, 5501, "Wireless Headphones", 199.00, "2026-04-15", "2026-04-18", "DELIVERED", "WEB"),
    (9002, 5502, "Ceramic Knife Set", 89.00, "2026-05-30", "2026-06-02", "DELIVERED", "WEB"),
    (9003, 5503, "E-book: Oracle 26ai Guide", 29.00, "2026-06-01", "2026-06-01", "DELIVERED", "MOBILE"),
    (9004, 5504, "Standing Desk", 420.00, "2026-05-20", "2026-06-03", "DELIVERED", "WEB"),
]

# request_id, order_id, reason_text
REQUESTS = [
    (7001, 9001, "I changed my mind and no longer want the headphones. I'd like to return them for a refund."),
    (7002, 9002, "The knife set arrived with two cracked blades — it was damaged in the box on arrival."),
    (7003, 9003, "I want a refund for the e-book; I already downloaded and read most of it though."),
]

CREATE = [
    "CREATE TABLE orders (order_id NUMBER PRIMARY KEY, customer_id NUMBER, product VARCHAR2(120), "
    "amount NUMBER, order_date DATE, delivered_date DATE, status VARCHAR2(20), channel VARCHAR2(20))",
    "CREATE TABLE refund_requests (request_id NUMBER PRIMARY KEY, order_id NUMBER, "
    "reason_text VARCHAR2(2000), requested_at TIMESTAMP DEFAULT SYSTIMESTAMP)",
    f"CREATE TABLE policies (policy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
    f"title VARCHAR2(120), category VARCHAR2(30), clause_text VARCHAR2(2000), "
    f"embedding VECTOR({config.EMBED_DIM}, FLOAT32))",
]


def _q(text: str) -> str:
    t = (text or "").replace("'", "''")
    if "&" in t:
        return "'" + t.replace("&", "'||CHR(38)||'") + "'"
    return "'" + t + "'"


def _date(d: str) -> str:
    return f"TO_DATE('{d}','YYYY-MM-DD')"


async def _run(mcp: OracleMCP, sql: str, what: str) -> None:
    out = await mcp.run_sql(sql)
    if "ORA-" in out or "Error" in out or "cancelled" in out:
        ora = next((ln for ln in out.splitlines() if "ORA-" in ln), out[:400])
        raise RuntimeError(f"{what} FAILED:\n{ora}")
    print(f"  · {what}")


async def main() -> None:
    client = AsyncOpenAI(api_key=config.OPENAI_API_KEY or None)
    print(f"Embedding {len(POLICIES)} policy clauses with {config.EMBED_MODEL} ...")
    emb = await client.embeddings.create(model=config.EMBED_MODEL,
                                         input=[f"{t}. {c}" for (t, _cat, c) in POLICIES])
    vectors = [d.embedding for d in emb.data]

    async with open_oracle_mcp(config.SQLCL_COMMAND, config.ORACLE_MCP_CONNECTION) as mcp:
        print(f"Connected via SQLcl MCP (connection '{config.ORACLE_MCP_CONNECTION}').\n")
        await mcp.run_sqlcl("set define off")

        print("Creating tables ...")
        for tbl in ("REFUND_REQUESTS", "ORDERS", "POLICIES"):
            await mcp.run_sql(f"BEGIN EXECUTE IMMEDIATE 'DROP TABLE {tbl} CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;")
        for ddl in CREATE:
            await _run(mcp, ddl, ddl.split()[2])

        print("Loading orders ...")
        rows = "\n".join(
            f"  INTO orders VALUES ({oid},{cid},{_q(p)},{amt},{_date(od)},{_date(dd)},{_q(st)},{_q(ch)})"
            for (oid, cid, p, amt, od, dd, st, ch) in ORDERS)
        await _run(mcp, f"INSERT ALL\n{rows}\nSELECT 1 FROM DUAL", "orders")

        print("Loading refund requests ...")
        rows = "\n".join(
            f"  INTO refund_requests (request_id, order_id, reason_text) VALUES ({rid},{oid},{_q(rt)})"
            for (rid, oid, rt) in REQUESTS)
        await _run(mcp, f"INSERT ALL\n{rows}\nSELECT 1 FROM DUAL", "refund_requests")

        print("Loading policies + embeddings ...")
        for (t, cat, c), vec in zip(POLICIES, vectors):
            await mcp.run_sql(
                "INSERT INTO policies (title, category, clause_text, embedding) VALUES "
                f"({_q(t)},{_q(cat)},{_q(c)},TO_VECTOR('{_vector_literal(vec)}'))")
        print(f"  · {len(POLICIES)} policies loaded")

        print("Building HNSW vector index ...")
        try:
            await mcp.run_sql("DROP INDEX policies_hnsw_idx")
        except Exception:
            pass
        try:
            await mcp.run_sql(
                "CREATE VECTOR INDEX policies_hnsw_idx ON policies (embedding) "
                "ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE WITH TARGET ACCURACY 95")
            print("  · index created")
        except Exception as exc:
            print(f"  ! Skipping vector index ({exc}). Exact search will be used.")

        await mcp.run_sql("COMMIT")
        print("\nDone. Seed complete.")


if __name__ == "__main__":
    asyncio.run(main())
