-- ============================================================================
--  Hybrid-RAG Refund Copilot — reference schema
--  policies = unstructured (vector), orders = structured, refund_requests = input.
--  seed.py creates these and fills the embeddings.
-- ============================================================================

CREATE TABLE orders (
  order_id       NUMBER PRIMARY KEY,
  customer_id    NUMBER,
  product        VARCHAR2(120),
  amount         NUMBER,
  order_date     DATE,
  delivered_date DATE,
  status         VARCHAR2(20),
  channel        VARCHAR2(20)
);

CREATE TABLE refund_requests (
  request_id   NUMBER PRIMARY KEY,
  order_id     NUMBER,
  reason_text  VARCHAR2(2000),
  requested_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE policies (
  policy_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR2(120),
  category     VARCHAR2(30),
  clause_text  VARCHAR2(2000),
  embedding    VECTOR(1536, FLOAT32)
);

CREATE VECTOR INDEX policies_hnsw_idx
  ON policies (embedding)
  ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE WITH TARGET ACCURACY 95;

-- The hybrid query the copilot runs — vectors + tables in ONE statement:
--   SELECT r.request_id, o.*, TRUNC(SYSDATE - o.delivered_date) days_since_delivery,
--          p.title, p.clause_text,
--          VECTOR_DISTANCE(p.embedding, :qvec, COSINE) AS policy_distance
--   FROM   refund_requests r
--   JOIN   orders o ON o.order_id = r.order_id
--   CROSS JOIN LATERAL (
--     SELECT title, clause_text, embedding FROM policies
--     ORDER BY VECTOR_DISTANCE(embedding, :qvec, COSINE) FETCH FIRST 2 ROWS ONLY
--   ) p
--   WHERE r.request_id = :rid;
